#!/bin/bash

ACTIVE_WORKSPACE=$(hyprctl monitors | grep -C 5 "focused: yes" | grep active | awk '{print $3}')
echo $ACTIVE_WORKSPACE
NEXT_WORKSPACE=$(expr $ACTIVE_WORKSPACE + 1)

if (($NEXT_WORKSPACE == 6)) || (($NEXT_WORKSPACE == 10)); then
  exit 0
fi

hyprctl dispatch workspace $NEXT_WORKSPACE
